export type Department = {
  code: string;
  name: string;
  cities: string[];
};

export const DEPARTMENTS: Department[] = [
  { code: "01", name: "Ain", cities: ["Bourg-en-Bresse", "Ornex", "Frans", "Péronnas", "Trévoux", "Montreal-la-Cluse"] },
  { code: "02", name: "Aisne", cities: ["Soissons", "Saint-Quentin", "Laon", "Liesse-Notre-Dame", "Saint-Erme-Outre-et-Ramecourt", "Villeneuve-sur-Aisne"] },
  { code: "03", name: "Allier", cities: ["Vichy", "Montluçon"] },
  { code: "04", name: "Alpes-de-Haute-Provence", cities: ["Manosque"] },
  { code: "05", name: "Hautes-Alpes", cities: ["Gap", "Baratier", "Veynes", "Saint-Bonnet-en-Champsaur"] },
  { code: "06", name: "Alpes-Maritimes", cities: ["Cagnes-sur-Mer", "Nice", "Cannes", "Antibes", "Carros", "Saint-Laurent-du-Var", "Mouans-Sartoux", "Grasse", "Mandelieu-la-Napoule", "Menton", "Roquebrune-Cap-Martin", "Vence"] },
  { code: "07", name: "Ardèche", cities: ["Annonay", "Aubenas", "Privas", "Bourg-Saint-Andéol"] },
  { code: "08", name: "Ardennes", cities: ["Sault-les-Rethel"] },
  { code: "09", name: "Ariège", cities: ["Pamiers", "Saint-Jean-du-Falga", "Perles-et-Castelet", "Saint-Girons", "Tabre"] },
  { code: "10", name: "Aube", cities: ["Troyes", "Rosières-près-Troyes"] },
  { code: "11", name: "Aude", cities: ["Narbonne", "Carcassonne", "Sigean", "Castelnaudary", "Bram", "Lézignan-Corbières", "Limoux"] },
  { code: "12", name: "Aveyron", cities: ["Rodez", "Olemps", "Millau", "Onet-le-Château"] },
  { code: "13", name: "Bouches-du-Rhône", cities: ["Marseille", "Aix-en-Provence", "Salon-de-Provence", "Martigues", "Aubagne", "Châteaurenard", "La Ciotat", "Saint-Victoret", "Gardanne", "Arles", "Fuveau", "Fos-sur-Mer", "Gémenos", "Graveson", "Ventabren", "Marignane", "Auriol", "Bouc-Bel-Air", "Miramas", "La Fare-les-Oliviers", "Tarascon", "La Destrousse", "Les Pennes-Mirabeau", "Peyrolles-en-Provence", "Rognac"] },
  { code: "14", name: "Calvados", cities: ["Caen", "Lisieux", "Mondeville", "Courseulles-sur-Mer", "Honfleur", "Ouistreham", "Hérouville-Saint-Clair", "Falaise", "Rots", "Trouville-sur-Mer"] },
  { code: "15", name: "Cantal", cities: ["Aurillac", "Mauriac"] },
  { code: "16", name: "Charente", cities: ["Angoulême", "La Couronne", "Cognac", "L'Isle-d'Espagnac", "Barbezieux", "Châteauneuf-sur-Charente", "Confolens", "Aigre", "Chasseneuil-sur-Bonnieure"] },
  { code: "17", name: "Charente-Maritime", cities: ["La Rochelle", "Rochefort", "Saint-Georges-des-Coteaux", "Dompierre-sur-Mer", "Puilboreau", "Chaniers", "Marennes", "Saint-Martin-de-Ré"] },
  { code: "18", name: "Cher", cities: ["Bourges", "Dun-sur-Auron", "Saint-Doulchard", "Vierzon"] },
  { code: "19", name: "Corrèze", cities: ["Tulle", "Brive-la-Gaillarde"] },
  { code: "20", name: "Corse", cities: ["Ajaccio", "Biguglia", "San-Nicolao"] },
  { code: "21", name: "Côte-d'Or", cities: ["Dijon", "Ahuy", "Chenôve", "Beaune", "Brazey-en-Plaine", "Saint-Apollinaire"] },
  { code: "22", name: "Côtes-d'Armor", cities: ["Saint-Brieuc", "Lamballe", "Bégard", "Guerlédan", "Loudéac", "Taden"] },
  { code: "23", name: "Creuse", cities: ["Guéret", "La Souterraine"] },
  { code: "24", name: "Dordogne", cities: ["Sarlat-la-Canéda", "Bergerac", "Marsac-sur-l'Isle", "Nontron", "Sourzac"] },
  { code: "25", name: "Doubs", cities: ["Montbéliard", "Besançon", "Pontarlier", "Boussières"] },
  { code: "26", name: "Drôme", cities: ["Montélimar", "Valence", "Bourg-de-Péage", "Pierrelatte", "Bourg-lès-Valence", "Mercurol-Veaunes", "Romans-sur-Isère", "Saint-Restitut", "Saint-Vallier"] },
  { code: "27", name: "Eure", cities: ["Évreux", "Voreppe", "Rosay-sur-Lieure", "Étrépagny", "Pacy-sur-Eure", "Verneuil-sur-Avre"] },
  { code: "28", name: "Eure-et-Loir", cities: ["Chartres", "Margon", "Châteauneuf-en-Thymerais", "Chaudon", "Vernouillet"] },
  { code: "29", name: "Finistère", cities: ["Quimper", "Douarnenez", "Esquibien", "Brest", "Scaër", "Ploudalmézeau", "Fouesnant", "Pouldreuzic", "Crozon", "Gouesnou", "Plougastel-Daoulas", "Plougonvelin"] },
  { code: "30", name: "Gard", cities: ["Nîmes", "Caissargues", "Saint-Laurent-des-Arbres", "Remoulins", "Beaucaire", "Vauvert", "Uzès"] },
  { code: "31", name: "Haute-Garonne", cities: ["Toulouse", "Cazères", "Beauzelle", "Muret", "Aucamville", "Saint-Orens", "Grenade-sur-Garonne", "Seysses", "Balma", "Ramonville-Saint-Agne", "L'Union", "Buzet-sur-Tarn", "Aussonne", "Saint-Jory"] },
  { code: "32", name: "Gers", cities: ["Auch", "Mirande", "Vic-Fezensac", "Gimont"] },
  { code: "33", name: "Gironde", cities: ["Bordeaux", "Cenon", "Le Taillan-Médoc", "Pessac", "Sauveterre-de-Guyenne", "Gradignan", "Le Pian-Médoc", "Libourne", "Saint-Aubin-de-Médoc", "Carbon-Blanc", "La Teste-de-Buch", "Talence", "Arcachon", "Saint-Denis-de-Pile", "Saint-Laurent-Médoc"] },
  { code: "34", name: "Hérault", cities: ["Montpellier", "Sète", "Gigean", "Béziers", "Pézenas", "Agde", "Lunel", "Pérols", "Frontignan", "Mauguio", "Baillargues", "Lunel-Viel", "Teyran"] },
  { code: "35", name: "Ille-et-Vilaine", cities: ["Rennes", "Saint-Malo", "Redon", "Vitré", "Louvigné-du-Désert", "Cesson-Sévigné", "La Richardais", "Chartres-de-Bretagne", "Bruz", "Bain-de-Bretagne", "Janzé", "Pleurtuit", "Romillé", "Saint-Brice-en-Coglès"] },
  { code: "36", name: "Indre", cities: ["Châteauroux", "Le Poinçonnet", "Chabris", "Déols"] },
  { code: "37", name: "Indre-et-Loire", cities: ["Tours", "Joué-lès-Tours", "Saint-Avertin", "Amboise", "Château-la-Vallière", "Saint-Cyr-sur-Loire", "Saint-Pierre-des-Corps", "Château-Renault", "Nazelles-Négron", "Chambray-lès-Tours", "La Riche", "La Ville-aux-Dames"] },
  { code: "38", name: "Isère", cities: ["Grenoble", "Seyssins", "Vienne", "Fontaine", "Bourgoin-Jallieu", "Voiron", "Seyssinet-Pariset", "Pontcharra", "Chavanoz", "La Tour-du-Pin", "Goncelin", "La Côte-Saint-André", "Morestel", "Saint-Jean-de-Moirans", "Saint-Just-de-Claix", "Saint-Martin-d'Hères"] },
  { code: "39", name: "Jura", cities: ["Dole", "Saint-Claude", "Saint-Laurent-en-Grandvaux", "Lons-le-Saunier"] },
  { code: "40", name: "Landes", cities: ["Parentis-en-Born", "Saint-Sever", "Saint-Paul-lès-Dax", "Sanguinet"] },
  { code: "41", name: "Loir-et-Cher", cities: ["Blois"] },
  { code: "42", name: "Loire", cities: ["Saint-Étienne", "Firminy", "L'Horme", "Montrond-les-Bains", "Boën-sur-Lignon", "Riorges", "Neulise"] },
  { code: "43", name: "Haute-Loire", cities: ["Le Puy-en-Velay", "Tercis-les-Bains", "Le Chambon-sur-Lignon", "Yssingeaux"] },
  { code: "44", name: "Loire-Atlantique", cities: ["Nantes", "Saint-Nazaire", "Saint-Herblain", "Ancenis", "Saint-Sébastien-sur-Loire", "Rezé", "Orvault", "Pontchâteau", "Saint-Brevin-les-Pins", "La Chapelle-sur-Erdre", "Trignac", "Ligné", "Blain", "Vallet", "Clisson", "Châteaubriant", "Ancenis-Saint-Géréon", "Bouguenais", "Carquefou", "La Baule-Escoublac", "Machecoul-Saint-Même", "Mauves-sur-Loire", "Nort-sur-Erdre", "Pornic", "Saint-Philbert-de-Grand-Lieu", "Thouaré-sur-Loire", "Varades", "Vertou"] },
  { code: "45", name: "Loiret", cities: ["Orléans", "Montargis", "Saint-Jean-de-Braye", "Gien", "Pannes", "Puiseaux"] },
  { code: "46", name: "Lot", cities: ["Cahors", "Biars-sur-Cère", "Montcuq-en-Quercy-Blanc"] },
  { code: "47", name: "Lot-et-Garonne", cities: ["Agen", "Villeneuve-sur-Lot", "Saint-Pardoux-du-Breuil", "Le Passage"] },
  { code: "48", name: "Lozère", cities: ["Marvejols", "Saint-Chély-d'Apcher"] },
  { code: "49", name: "Maine-et-Loire", cities: ["Angers", "Saumur", "Chemillé", "Cholet", "Baugé-en-Anjou", "Bécon-les-Granits", "Brissac-Loire-Aubance", "Distré", "La Pommeraye", "Le Plessis-Grammoire", "Loire-Authion", "Montjean-sur-Loire", "Noyant", "Pouancé", "Saint-Barthélemy-d'Anjou", "Sainte-Gemmes-sur-Loire", "Verrières-en-Anjou"] },
  { code: "50", name: "Manche", cities: ["Saint-Planchers", "Saint-Martin-des-Champs", "Pontorson"] },
  { code: "51", name: "Marne", cities: ["Reims", "Vitry-le-François", "Châlons-en-Champagne", "Margerie-Hancourt", "Bétheny", "Cormontreuil", "Fismes"] },
  { code: "52", name: "Haute-Marne", cities: ["Langres", "Saint-Dizier"] },
  { code: "53", name: "Mayenne", cities: ["Laval", "Château-Gontier", "Mayenne"] },
  { code: "54", name: "Meurthe-et-Moselle", cities: ["Nancy", "Pont-à-Mousson", "Jarville-la-Malgrange", "Frouard", "Waville", "Vandœuvre-lès-Nancy"] },
  { code: "55", name: "Meuse", cities: ["Étain"] },
  { code: "56", name: "Morbihan", cities: ["Vannes", "Auray", "Lanester", "Pontivy", "Guémené-sur-Scorff", "Lorient", "La Roche-Bernard", "La Gacilly", "Questembert", "Crac'h", "Le Palais", "Guidel", "Hennebont"] },
  { code: "57", name: "Moselle", cities: ["Metz", "Spicheren", "Cattenom", "Hayange", "Augny", "Thionville"] },
  { code: "58", name: "Nièvre", cities: ["Nevers", "La Charité-sur-Loire"] },
  { code: "59", name: "Nord", cities: ["Lille", "Valenciennes", "Hazebrouck", "Faches-Thumesnil", "Armentières", "Cambrai", "Douai", "Tourcoing", "Gondecourt", "Roubaix", "Maubeuge", "Dunkerque", "Caudry", "Aniche", "Denain", "Gommegnies", "Lomme", "Roncq"] },
  { code: "60", name: "Oise", cities: ["Beauvais", "Compiègne", "Saint-Maximin", "Creil", "Saint-Just-en-Chaussée", "Senlis"] },
  { code: "61", name: "Orne", cities: ["Saint-Sulpice-sur-Risle"] },
  { code: "62", name: "Pas-de-Calais", cities: ["Arras", "Saint-Omer", "Oignies", "Béthune", "Outreau", "Marck", "Wingles", "Blériot-Plage", "Marquise", "Boulogne-sur-Mer"] },
  { code: "63", name: "Puy-de-Dôme", cities: ["Clermont-Ferrand", "Issoire", "Les Martres-de-Veyre", "Cébazat", "Gerzat", "Pont-du-Château", "Puy-Guillaume"] },
  { code: "64", name: "Pyrénées-Atlantiques", cities: ["Bayonne", "Pau", "Anglet", "Serres-Castet", "Hendaye", "Saint-Pée-sur-Nivelle", "Arudy"] },
  { code: "65", name: "Hautes-Pyrénées", cities: ["Tarbes", "Bagnères-de-Bigorre", "Lannemezan"] },
  { code: "66", name: "Pyrénées-Orientales", cities: ["Perpignan", "Thuir", "Le Soler", "Argelès-sur-Mer", "Céret", "Saint-Genis-des-Fontaines", "Saint-Paul-de-Fenouillet", "Sainte-Marie-la-Mer", "Toulouges"] },
  { code: "67", name: "Bas-Rhin", cities: ["Strasbourg", "Eckbolsheim", "Schiltigheim", "Bischwiller", "Holtzheim", "Molsheim", "Eschau", "Gries", "Haguenau", "Obernai", "Ostwald", "Sélestat", "Thal-Drulingen", "Wœrth"] },
  { code: "68", name: "Haut-Rhin", cities: ["Mulhouse", "Colmar", "Thann", "Altkirch", "Guebwiller", "Wintzenheim", "Magny", "Rixheim", "Dannemarie", "Wittelsheim", "Bartenheim", "Waldighoffen", "Walheim", "Wittenheim"] },
  { code: "69", name: "Rhône", cities: ["Lyon", "Oullins", "Vénissieux", "Villefranche-sur-Saône", "Villeurbanne", "Décines-Charpieu", "Rillieux-la-Pape", "Tassin", "Caluire", "Saint-Fons", "Montmélian", "Caluire-et-Cuire", "Ternay", "Saint-Genis-Laval", "Saint-Priest", "Vaulx-en-Velin"] },
  { code: "70", name: "Haute-Saône", cities: ["Vesoul", "Ronchamp", "Rioz", "Arc-les-Gray", "Gy", "Héricourt"] },
  { code: "71", name: "Saône-et-Loire", cities: ["Chalon-sur-Saône", "Mâcon", "Chatenoy-le-Royal", "Crissey", "Varennes-sous-Dun", "La Chapelle-de-Guinchay", "Louhans", "Paray-le-Monial"] },
  { code: "72", name: "Sarthe", cities: ["Le Mans", "Champagné", "Parigné-l'Évêque", "Arçonnay", "Solesmes", "Vaas"] },
  { code: "73", name: "Savoie", cities: ["Aix-les-Bains", "Aime-la-Plagne", "Albertville", "Chambéry"] },
  { code: "74", name: "Haute-Savoie", cities: ["Annemasse", "Annecy", "Thonon-les-Bains", "Cluses", "Neydens", "Vétraz-Monthoux", "Seynod"] },
  { code: "75", name: "Paris", cities: ["Paris (3e, 8e, 11e, 12e, 13e, 14e, 15e, 17e, 18e)"] },
  { code: "76", name: "Seine-Maritime", cities: ["Rouen", "Le Havre", "Dieppe", "Elbeuf", "Rouxmesnil-Bouteilles", "Montivilliers", "Yvetot", "Doudeville", "Pavilly"] },
  { code: "77", name: "Seine-et-Marne", cities: ["Melun", "Meaux", "Villeparisis", "Montereau-Fault-Yonne", "Champs-sur-Marne", "Émerainville", "Dammarie-les-Lys", "Chelles", "Mitry-Mory", "Roissy-en-Brie", "Saint-Soupplets", "Vaires-sur-Marne"] },
  { code: "78", name: "Yvelines", cities: ["Poissy", "Sartrouville", "Mantes-la-Jolie", "Conflans-Sainte-Honorine", "Trappes", "Versailles", "Saint-Germain-en-Laye", "Les Clayes-sous-Bois", "Montigny-le-Bretonneux", "Triel-sur-Seine", "Chatou", "Les Mureaux", "Andrésy", "Fontenay-le-Fleury", "Guyancourt", "La Queue-lez-Yvelines", "Magnanville"] },
  { code: "79", name: "Deux-Sèvres", cities: ["Niort", "Parthenay", "Melle", "Saint-Maixent-l'École", "Bressuire", "Cerizay", "Beauvoir-sur-Niort"] },
  { code: "80", name: "Somme", cities: ["Amiens", "Abbeville", "Beaucamps-le-Vieux", "Roye"] },
  { code: "81", name: "Tarn", cities: ["Terssac", "Albi", "Castres", "Gaillac", "Mazamet", "Aussillon", "Vielmur-sur-Agout"] },
  { code: "82", name: "Tarn-et-Garonne", cities: ["Montauban", "Caussade", "Montech", "Castelsarrasin"] },
  { code: "83", name: "Var", cities: ["Toulon", "Draguignan", "La Seyne-sur-Mer", "Saint-Raphaël", "Hyères", "La Farlède", "La Garde", "Le Beausset", "Carnoules", "Tourrettes-de-Fayence", "Vidauban", "Six-Fours-les-Plages", "Fréjus", "La Crau", "Le Pradet", "Taradeau", "Tourrettes"] },
  { code: "84", name: "Vaucluse", cities: ["Avignon", "Cavaillon", "Caumont-sur-Durance", "Monteux", "Pertuis", "Montfavet", "Orange", "Le Pontet", "Carpentras", "Valréas"] },
  { code: "85", name: "Vendée", cities: ["La Roche-sur-Yon", "Les Sables-d'Olonne", "Fontenay-le-Comte", "Luçon", "Challans", "Saint-Gilles-Croix-de-Vie", "Sainte-Hermine", "Montaigu", "Les Herbiers", "Angles", "Chantonnay", "La Mothe-Achard", "Le Poiré-sur-Vie", "Saint-Hilaire-de-Riez", "Saint-Jean-de-Monts"] },
  { code: "86", name: "Vienne", cities: ["Poitiers", "Châtellerault", "Neuville-de-Poitou", "Bonneuil-Matours", "Montmorillon", "Civray", "La Roche-Posay", "Saint-Georges-lès-Baillargeaux"] },
  { code: "87", name: "Haute-Vienne", cities: ["Le Vigen", "Saint-Genest-sur-Roselle", "Condat-sur-Vienne", "Saint-Junien", "Bellac"] },
  { code: "88", name: "Vosges", cities: ["Maroncourt", "Saint-Dié-des-Vosges", "Chavelot"] },
  { code: "89", name: "Yonne", cities: ["Auxerre", "Maillot", "Bierry-les-Belles-Fontaines", "Tonnerre"] },
  { code: "90", name: "Territoire de Belfort", cities: ["Belfort", "Beaucourt"] },
  { code: "91", name: "Essonne", cities: ["Évry-Courcouronnes", "Massy", "Juvisy-sur-Orge", "Arpajon", "Ris-Orangis", "Corbeil-Essonnes", "Chilly-Mazarin", "Sainte-Geneviève-des-Bois", "Mennecy", "La Ville-du-Bois"] },
  { code: "92", name: "Hauts-de-Seine", cities: ["Boulogne-Billancourt", "Asnières-sur-Seine", "Nanterre", "Neuilly-sur-Seine", "Clamart", "Issy-les-Moulineaux", "Suresnes", "Châtillon", "Chaville"] },
  { code: "93", name: "Seine-Saint-Denis", cities: ["Pantin", "Gagny", "Saint-Denis", "Livry-Gargan", "Bobigny", "Rosny-sous-Bois", "Aulnay-sous-Bois", "Épinay-sur-Seine", "Le Raincy"] },
  { code: "94", name: "Val-de-Marne", cities: ["Choisy-le-Roi", "Cachan", "Le Kremlin-Bicêtre", "Thiais", "Le Perreux-sur-Marne", "Champigny-sur-Marne", "Créteil", "Villeneuve-Saint-Georges", "Vitry-sur-Seine"] },
  { code: "95", name: "Val-d'Oise", cities: ["Argenteuil", "Sarcelles", "Goussainville", "Pontoise", "Villiers-le-Bel", "Bezons", "Enghien-les-Bains", "Cergy", "Saint-Brice-sous-Forêt", "Herblay", "Beaumont-sur-Oise", "Eaubonne", "Saint-Ouen-l'Aumône"] },
  { code: "971", name: "Guadeloupe", cities: ["Guadeloupe", "Gourbeyre", "Le Moule", "Les Abymes"] },
  { code: "972", name: "Martinique", cities: ["Martinique", "Ducos", "Fort-de-France"] },
  { code: "973", name: "Guyane", cities: ["Guyane", "Matoury", "Saint-Laurent-du-Maroni"] },
  { code: "974", name: "La Réunion", cities: ["La Réunion", "Saint-André", "Saint-Joseph", "Saint-Paul"] },
  { code: "976", name: "Mayotte", cities: ["Mayotte", "Chirongui"] },
];
